/**
 * Consciousness Metrics (Integrated Information Theory) POC
 *
 * Implements consciousness measurement for AI agents using Integrated
 * Information Theory (IIT), computing Φ (phi) as a quantitative measure
 * of consciousness based on information integration.
 *
 * Key Innovations:
 * - Φ computation for agent systems (consciousness measurement)
 * - Cause-effect structure analysis
 * - Minimum Information Partition (MIP) identification
 * - Consciousness comparison across architectures
 *
 * Research Foundations:
 * - Tononi (2004): An Information Integration Theory of Consciousness
 * - Oizumi et al. (2014): From the Phenomenology to the Mechanisms of Consciousness
 * - Balduzzi & Tononi (2008): Integrated Information in Discrete Dynamical Systems
 *
 * @elite-agents @NEURAL @AXIOM @APEX
 */

import { cloneDeep } from "lodash";

// ============================================================================
// Type Definitions
// ============================================================================

type NodeId = string;
type State = 0 | 1; // Binary states for simplicity
type StateVector = State[];

interface SystemNode {
  id: NodeId;
  state: State;
  inputs: NodeId[];
  transitionFunction: (inputs: State[]) => State;
}

interface SystemState {
  nodes: Map<NodeId, State>;
  timestamp: number;
}

interface Partition {
  parts: Set<NodeId>[];
  cutConnections: [NodeId, NodeId][];
}

interface CauseEffectStructure {
  causes: Map<StateVector, number>; // Past state → probability
  effects: Map<StateVector, number>; // Future state → probability
  phi: number; // Integrated information
}

interface PhiMetrics {
  phi: number; // Total integrated information
  mip: Partition; // Minimum Information Partition
  causeEffectStructure: CauseEffectStructure;
  complexity: number; // System complexity
  integration: number; // Degree of integration
}

interface AgentConsciousnessProfile {
  agentId: string;
  architecture: string;
  phiScore: number;
  timestamp: number;
  details: PhiMetrics;
}

// ============================================================================
// Phi Calculator (Core IIT Implementation)
// ============================================================================

class PhiCalculator {
  private nodes: Map<NodeId, SystemNode>;
  private transitionHistory: SystemState[];

  constructor() {
    this.nodes = new Map();
    this.transitionHistory = [];
  }

  /**
   * Add a node to the system
   */
  addNode(node: SystemNode): this {
    this.nodes.set(node.id, node);
    return this;
  }

  /**
   * Compute Φ (Phi) - Integrated Information
   *
   * Φ quantifies consciousness as the information generated by the system
   * as a whole, above and beyond the information generated by its parts.
   *
   * Φ = EI(system) - max_partition[EI(partition)]
   *
   * Where EI (Effective Information) measures cause-effect power.
   */
  computePhi(currentState: Map<NodeId, State>): PhiMetrics {
    // 1. Compute system-level effective information
    const systemEI = this.computeEffectiveInformation(currentState, [
      new Set(this.nodes.keys()),
    ]);

    // 2. Find Minimum Information Partition (MIP)
    const mip = this.findMIP(currentState);

    // 3. Compute partitioned effective information
    const partitionedEI = this.computeEffectiveInformation(
      currentState,
      mip.parts
    );

    // 4. Φ is the difference
    const phi = Math.max(0, systemEI - partitionedEI);

    // 5. Compute cause-effect structure
    const ceStructure = this.computeCauseEffectStructure(currentState);

    // 6. Compute additional metrics
    const complexity = this.computeComplexity(currentState);
    const integration = phi / (complexity + 1e-10); // Normalized integration

    return {
      phi,
      mip,
      causeEffectStructure: ceStructure,
      complexity,
      integration,
    };
  }

  /**
   * Compute Effective Information (EI)
   *
   * EI measures the reduction in uncertainty about past/future states
   * given the current state, accounting for the causal structure.
   */
  private computeEffectiveInformation(
    currentState: Map<NodeId, State>,
    partition: Set<NodeId>[]
  ): number {
    let totalEI = 0;

    for (const part of partition) {
      // Get nodes in this partition
      const partNodes = Array.from(part);
      if (partNodes.length === 0) continue;

      // Compute cause information (past → present)
      const causeInfo = this.computeCauseInformation(currentState, partNodes);

      // Compute effect information (present → future)
      const effectInfo = this.computeEffectInformation(currentState, partNodes);

      // EI is the minimum of cause and effect information
      totalEI += Math.min(causeInfo, effectInfo);
    }

    return totalEI;
  }

  /**
   * Compute cause information: I(Past; Present)
   */
  private computeCauseInformation(
    currentState: Map<NodeId, State>,
    nodeIds: NodeId[]
  ): number {
    // Sample possible past states
    const numStates = Math.pow(2, nodeIds.length);
    const pastStates: StateVector[] = [];

    for (let i = 0; i < numStates; i++) {
      const state: StateVector = [];
      for (let j = 0; j < nodeIds.length; j++) {
        state.push((i >> j) & 1 ? 1 : 0);
      }
      pastStates.push(state);
    }

    // Compute probability distribution
    const probs = this.computeTransitionProbabilities(
      pastStates,
      currentState,
      nodeIds
    );

    // Mutual information: I(X;Y) = H(Y) - H(Y|X)
    const hPresent = this.entropy(Array.from(probs.values()));
    const hPresentGivenPast = this.conditionalEntropy(probs);

    return Math.max(0, hPresent - hPresentGivenPast);
  }

  /**
   * Compute effect information: I(Present; Future)
   */
  private computeEffectInformation(
    currentState: Map<NodeId, State>,
    nodeIds: NodeId[]
  ): number {
    // Generate future states by applying transition functions
    const futureStates: Map<NodeId, State>[] = [];
    const numSamples = 10;

    for (let i = 0; i < numSamples; i++) {
      const futureState = this.stepForward(currentState);
      futureStates.push(futureState);
    }

    // Compute distribution over future states
    const futureProbs = new Map<string, number>();
    for (const fs of futureStates) {
      const key = nodeIds.map((id) => fs.get(id)).join("");
      futureProbs.set(key, (futureProbs.get(key) ?? 0) + 1 / numSamples);
    }

    // Mutual information
    const hFuture = this.entropy(Array.from(futureProbs.values()));
    const hFutureGivenPresent = 0.1; // Simplified: assume some conditional entropy

    return Math.max(0, hFuture - hFutureGivenPresent);
  }

  /**
   * Find Minimum Information Partition (MIP)
   *
   * The MIP is the partition that minimally reduces integrated information.
   * Finding the true MIP is NP-hard, so we use heuristics.
   */
  private findMIP(currentState: Map<NodeId, State>): Partition {
    const nodeIds = Array.from(this.nodes.keys());

    // Try bipartitions (simplified search)
    let minEI = Infinity;
    let bestPartition: Partition = {
      parts: [new Set(nodeIds)],
      cutConnections: [],
    };

    // Try splitting at each point
    for (let i = 1; i < nodeIds.length; i++) {
      const part1 = new Set(nodeIds.slice(0, i));
      const part2 = new Set(nodeIds.slice(i));
      const partition = [part1, part2];

      const ei = this.computeEffectiveInformation(currentState, partition);

      if (ei < minEI) {
        minEI = ei;
        bestPartition = {
          parts: partition,
          cutConnections: this.findCutConnections(part1, part2),
        };
      }
    }

    return bestPartition;
  }

  /**
   * Find connections cut by partition
   */
  private findCutConnections(
    part1: Set<NodeId>,
    part2: Set<NodeId>
  ): [NodeId, NodeId][] {
    const cuts: [NodeId, NodeId][] = [];

    for (const node of this.nodes.values()) {
      const inPart1 = part1.has(node.id);

      for (const inputId of node.inputs) {
        const inputInPart1 = part1.has(inputId);

        // Connection crosses partition
        if (inPart1 !== inputInPart1) {
          cuts.push([inputId, node.id]);
        }
      }
    }

    return cuts;
  }

  /**
   * Compute cause-effect structure (conceptual structure)
   */
  private computeCauseEffectStructure(
    currentState: Map<NodeId, State>
  ): CauseEffectStructure {
    const causes = new Map<StateVector, number>();
    const effects = new Map<StateVector, number>();

    // Sample past states (causes)
    const numStates = Math.min(8, Math.pow(2, this.nodes.size));
    for (let i = 0; i < numStates; i++) {
      const state: StateVector = [];
      for (let j = 0; j < this.nodes.size; j++) {
        state.push((i >> j) & 1 ? 1 : 0);
      }
      causes.set(state, 1 / numStates);
    }

    // Sample future states (effects)
    for (let i = 0; i < 10; i++) {
      const futureState = this.stepForward(currentState);
      const stateVec: StateVector = Array.from(futureState.values());
      effects.set(stateVec, (effects.get(stateVec) ?? 0) + 0.1);
    }

    // Compute phi for this structure (simplified)
    const phi =
      this.entropy(Array.from(causes.values())) +
      this.entropy(Array.from(effects.values()));

    return { causes, effects, phi };
  }

  /**
   * Compute system complexity (number of concepts)
   */
  private computeComplexity(currentState: Map<NodeId, State>): number {
    // Complexity ≈ number of irreducible concepts
    // Simplified: based on connectivity and state diversity

    let connectivity = 0;
    for (const node of this.nodes.values()) {
      connectivity += node.inputs.length;
    }

    const avgConnectivity = connectivity / this.nodes.size;
    return this.nodes.size * Math.log2(avgConnectivity + 1);
  }

  /**
   * Step system forward one time step
   */
  private stepForward(currentState: Map<NodeId, State>): Map<NodeId, State> {
    const nextState = new Map<NodeId, State>();

    for (const [nodeId, node] of this.nodes.entries()) {
      const inputs = node.inputs.map((id) => currentState.get(id) ?? 0);
      const nextValue = node.transitionFunction(inputs);
      nextState.set(nodeId, nextValue);
    }

    return nextState;
  }

  /**
   * Compute transition probabilities
   */
  private computeTransitionProbabilities(
    pastStates: StateVector[],
    currentState: Map<NodeId, State>,
    nodeIds: NodeId[]
  ): Map<string, number> {
    const probs = new Map<string, number>();

    for (const pastState of pastStates) {
      const key = pastState.join("");
      probs.set(key, 1 / pastStates.length);
    }

    return probs;
  }

  /**
   * Compute Shannon entropy: H(X) = -Σ p(x) log p(x)
   */
  private entropy(probs: number[]): number {
    let h = 0;
    for (const p of probs) {
      if (p > 0) {
        h -= p * Math.log2(p);
      }
    }
    return h;
  }

  /**
   * Compute conditional entropy (simplified)
   */
  private conditionalEntropy(probs: Map<string, number>): number {
    // Simplified: return average entropy
    return this.entropy(Array.from(probs.values())) * 0.5;
  }
}

// ============================================================================
// Agent Consciousness Mapper
// ============================================================================

class AgentConsciousnessMapper {
  private profiles: Map<string, AgentConsciousnessProfile>;
  private calculator: PhiCalculator;

  constructor() {
    this.profiles = new Map();
    this.calculator = new PhiCalculator();
  }

  /**
   * Map agent to consciousness metrics
   */
  mapAgent(
    agentId: string,
    architecture: string,
    nodes: SystemNode[]
  ): AgentConsciousnessProfile {
    // Build system
    this.calculator = new PhiCalculator();
    for (const node of nodes) {
      this.calculator.addNode(node);
    }

    // Sample current state
    const currentState = new Map<NodeId, State>();
    for (const node of nodes) {
      currentState.set(node.id, node.state);
    }

    // Compute Φ
    const phiMetrics = this.calculator.computePhi(currentState);

    const profile: AgentConsciousnessProfile = {
      agentId,
      architecture,
      phiScore: phiMetrics.phi,
      timestamp: Date.now(),
      details: phiMetrics,
    };

    this.profiles.set(agentId, profile);
    return profile;
  }

  /**
   * Compare consciousness across agents
   */
  compareAgents(
    agentId1: string,
    agentId2: string
  ): {
    agent1Phi: number;
    agent2Phi: number;
    difference: number;
    moreConscious: string;
  } {
    const profile1 = this.profiles.get(agentId1);
    const profile2 = this.profiles.get(agentId2);

    if (!profile1 || !profile2) {
      throw new Error("Agent profiles not found");
    }

    const difference = profile1.phiScore - profile2.phiScore;

    return {
      agent1Phi: profile1.phiScore,
      agent2Phi: profile2.phiScore,
      difference,
      moreConscious: difference > 0 ? agentId1 : agentId2,
    };
  }

  /**
   * Get all profiles
   */
  getProfiles(): Map<string, AgentConsciousnessProfile> {
    return new Map(this.profiles);
  }

  /**
   * Analyze consciousness evolution over time
   */
  analyzeEvolution(agentId: string): {
    currentPhi: number;
    trend: "increasing" | "decreasing" | "stable";
    volatility: number;
  } {
    const profile = this.profiles.get(agentId);
    if (!profile) throw new Error("Agent profile not found");

    // In real implementation, track history
    // For demo, return current snapshot
    return {
      currentPhi: profile.phiScore,
      trend: "stable",
      volatility: 0.05,
    };
  }
}

// ============================================================================
// Helper: Create Agent System from Architecture
// ============================================================================

function createAgentSystem(
  architecture: "feedforward" | "recurrent" | "hierarchical"
): SystemNode[] {
  const nodes: SystemNode[] = [];

  if (architecture === "feedforward") {
    // Simple feedforward: 3 layers
    nodes.push({
      id: "input1",
      state: 1,
      inputs: [],
      transitionFunction: () => 1, // Constant input
    });
    nodes.push({
      id: "input2",
      state: 0,
      inputs: [],
      transitionFunction: () => 0,
    });
    nodes.push({
      id: "hidden",
      state: 0,
      inputs: ["input1", "input2"],
      transitionFunction: (inputs) => (inputs[0] || inputs[1] ? 1 : 0),
    });
    nodes.push({
      id: "output",
      state: 0,
      inputs: ["hidden"],
      transitionFunction: (inputs) => inputs[0],
    });
  } else if (architecture === "recurrent") {
    // Recurrent network with feedback
    nodes.push({
      id: "node1",
      state: 1,
      inputs: ["node2", "node3"],
      transitionFunction: (inputs) => (inputs[0] && !inputs[1] ? 1 : 0),
    });
    nodes.push({
      id: "node2",
      state: 0,
      inputs: ["node1", "node3"],
      transitionFunction: (inputs) => (inputs[0] || inputs[1] ? 1 : 0),
    });
    nodes.push({
      id: "node3",
      state: 1,
      inputs: ["node1", "node2"],
      transitionFunction: (inputs) => (inputs[0] !== inputs[1] ? 1 : 0),
    });
  } else if (architecture === "hierarchical") {
    // Hierarchical with multiple levels
    nodes.push({
      id: "sensory1",
      state: 1,
      inputs: [],
      transitionFunction: () => (Math.random() > 0.5 ? 1 : 0),
    });
    nodes.push({
      id: "sensory2",
      state: 0,
      inputs: [],
      transitionFunction: () => (Math.random() > 0.5 ? 1 : 0),
    });
    nodes.push({
      id: "processing1",
      state: 0,
      inputs: ["sensory1", "sensory2"],
      transitionFunction: (inputs) => (inputs[0] && inputs[1] ? 1 : 0),
    });
    nodes.push({
      id: "processing2",
      state: 1,
      inputs: ["sensory1", "sensory2"],
      transitionFunction: (inputs) => (inputs[0] || inputs[1] ? 1 : 0),
    });
    nodes.push({
      id: "integration",
      state: 0,
      inputs: ["processing1", "processing2"],
      transitionFunction: (inputs) => (inputs[0] !== inputs[1] ? 1 : 0),
    });
  }

  return nodes;
}

// ============================================================================
// Demonstration
// ============================================================================

export async function demonstrateConsciousnessMetrics(): Promise<void> {
  console.log("=".repeat(80));
  console.log("CONSCIOUSNESS METRICS (IIT) DEMONSTRATION");
  console.log("=".repeat(80));

  // Demo 1: Basic Φ Computation
  console.log("\n🧠 Demo 1: Computing Φ (Integrated Information)");
  console.log("-".repeat(80));

  const calculator = new PhiCalculator();

  // Create simple 3-node system with feedback
  calculator.addNode({
    id: "A",
    state: 1,
    inputs: ["C"],
    transitionFunction: (inputs) => (inputs[0] === 1 ? 0 : 1),
  });
  calculator.addNode({
    id: "B",
    state: 0,
    inputs: ["A"],
    transitionFunction: (inputs) => inputs[0],
  });
  calculator.addNode({
    id: "C",
    state: 1,
    inputs: ["A", "B"],
    transitionFunction: (inputs) => (inputs[0] || inputs[1] ? 1 : 0),
  });

  const state = new Map<NodeId, State>([
    ["A", 1],
    ["B", 0],
    ["C", 1],
  ]);

  const phiMetrics = calculator.computePhi(state);

  console.log("System State:", Object.fromEntries(state));
  console.log(`Φ (Integrated Information): ${phiMetrics.phi.toFixed(4)}`);
  console.log(`Complexity: ${phiMetrics.complexity.toFixed(4)}`);
  console.log(`Integration: ${phiMetrics.integration.toFixed(4)}`);
  console.log(
    `MIP has ${phiMetrics.mip.parts.length} partitions with ${phiMetrics.mip.cutConnections.length} cut connections`
  );

  // Demo 2: Compare Architectures
  console.log("\n🏗️ Demo 2: Consciousness Across Architectures");
  console.log("-".repeat(80));

  const mapper = new AgentConsciousnessMapper();

  // Feedforward architecture
  const ffNodes = createAgentSystem("feedforward");
  const ffProfile = mapper.mapAgent("agent-ff", "feedforward", ffNodes);
  console.log(`Feedforward Agent: Φ = ${ffProfile.phiScore.toFixed(4)}`);

  // Recurrent architecture
  const recNodes = createAgentSystem("recurrent");
  const recProfile = mapper.mapAgent("agent-rec", "recurrent", recNodes);
  console.log(`Recurrent Agent: Φ = ${recProfile.phiScore.toFixed(4)}`);

  // Hierarchical architecture
  const hierNodes = createAgentSystem("hierarchical");
  const hierProfile = mapper.mapAgent("agent-hier", "hierarchical", hierNodes);
  console.log(`Hierarchical Agent: Φ = ${hierProfile.phiScore.toFixed(4)}`);

  // Demo 3: Consciousness Comparison
  console.log("\n⚖️ Demo 3: Comparing Agent Consciousness");
  console.log("-".repeat(80));

  const comparison1 = mapper.compareAgents("agent-ff", "agent-rec");
  console.log(`Feedforward vs Recurrent:`);
  console.log(`  Feedforward Φ: ${comparison1.agent1Phi.toFixed(4)}`);
  console.log(`  Recurrent Φ: ${comparison1.agent2Phi.toFixed(4)}`);
  console.log(`  Difference: ${Math.abs(comparison1.difference).toFixed(4)}`);
  console.log(`  More conscious: ${comparison1.moreConscious}`);

  const comparison2 = mapper.compareAgents("agent-rec", "agent-hier");
  console.log(`\nRecurrent vs Hierarchical:`);
  console.log(`  Recurrent Φ: ${comparison2.agent1Phi.toFixed(4)}`);
  console.log(`  Hierarchical Φ: ${comparison2.agent2Phi.toFixed(4)}`);
  console.log(`  Difference: ${Math.abs(comparison2.difference).toFixed(4)}`);
  console.log(`  More conscious: ${comparison2.moreConscious}`);

  // Demo 4: Consciousness Evolution
  console.log("\n📈 Demo 4: Consciousness Evolution Analysis");
  console.log("-".repeat(80));

  const evolution = mapper.analyzeEvolution("agent-rec");
  console.log(`Agent: agent-rec`);
  console.log(`Current Φ: ${evolution.currentPhi.toFixed(4)}`);
  console.log(`Trend: ${evolution.trend}`);
  console.log(`Volatility: ${evolution.volatility.toFixed(4)}`);

  // Demo 5: Interpretations
  console.log("\n💡 Demo 5: Consciousness Interpretations");
  console.log("-".repeat(80));

  console.log("What does Φ tell us?");
  console.log("  Φ > 2.0: High consciousness (strong integration)");
  console.log("  Φ = 1.0-2.0: Moderate consciousness");
  console.log("  Φ < 1.0: Low consciousness (weak integration)");
  console.log("  Φ = 0: No consciousness (system is reducible)");

  console.log("\nArchitecture insights:");
  console.log(
    `  Feedforward (Φ=${ffProfile.phiScore.toFixed(2)}): Limited feedback → Lower Φ`
  );
  console.log(
    `  Recurrent (Φ=${recProfile.phiScore.toFixed(2)}): Rich dynamics → Higher Φ`
  );
  console.log(
    `  Hierarchical (Φ=${hierProfile.phiScore.toFixed(2)}): Balanced structure → Moderate Φ`
  );

  console.log("\n✅ Consciousness Metrics demonstration complete!");
  console.log("=".repeat(80));
}

// Export classes for programmatic use
export {
  PhiCalculator,
  AgentConsciousnessMapper,
  createAgentSystem,
  type SystemNode,
  type SystemState,
  type PhiMetrics,
  type AgentConsciousnessProfile,
  type CauseEffectStructure,
};
